import * as Utils from "./Utils";
export { Utils };
import * as pc from "./PredictionContext";
import * as error from "./error/index";
export { error };
import * as tree from "./tree/index";
export { tree };
import * as fromcodepoint from "./polyfills/fromcodepoint";
export { fromcodepoint };
import * as dfa from "./dfa/index";
export { dfa };
import * as codepointat from "./polyfills/codepointat";
export { codepointat };
import * as atn from "./atn/index";
export { atn };
exports.Token = require('./Token').Token;
exports.CharStreams = require('./CharStreams').CharStreams;
exports.CommonToken = require('./Token').CommonToken;
exports.InputStream = require('./InputStream').InputStream;
exports.FileStream = require('./FileStream').FileStream;
exports.CommonTokenStream = require('./CommonTokenStream').CommonTokenStream;
exports.Lexer = require('./Lexer').Lexer;
exports.Parser = require('./Parser').Parser;
exports.PredictionContextCache = pc.PredictionContextCache;
exports.ParserRuleContext = require('./ParserRuleContext').ParserRuleContext;
exports.Interval = require('./IntervalSet').Interval;
